language: python
before_script:
  - sleep 3
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pylint
script:
  - pylint backprop_blobs.py
  - pylint backprop_object.py
  - pylint backprop_xor.py
